// @flow
export const TOKEN_OPERATOR_EXPONENT = 'TOKEN_OPERATOR_EXPONENT';
export const TOKEN_OPERATOR_MULTIPLY = 'TOKEN_OPERATOR_MULTIPLY';
export const TOKEN_OPERATOR_DIVIDE = 'TOKEN_OPERATOR_DIVIDE';
export const TOKEN_OPERATOR_ADD = 'TOKEN_OPERATOR_ADD';
export const TOKEN_OPERATOR_SUBTRACT = 'TOKEN_OPERATOR_SUBTRACT';
export const TOKEN_OPERATOR_NEGATE = 'TOKEN_OPERATOR_NEGATE';
export const TOKEN_OPERATOR_FACTORIAL = 'TOKEN_OPERATOR_FACTORIAL';
export const TOKEN_NUMBER = 'TOKEN_NUMBER';
export const TOKEN_UNIT_NAME = 'TOKEN_UNIT_NAME';
export const TOKEN_UNIT_PREFIX = 'TOKEN_UNIT_PREFIX';
export const TOKEN_UNIT_SUFFIX = 'TOKEN_UNIT_SUFFIX';
export const TOKEN_BRACKET_OPEN = 'TOKEN_BRACKET_OPEN';
export const TOKEN_BRACKET_CLOSE = 'TOKEN_BRACKET_CLOSE';
export const TOKEN_COLOR = 'TOKEN_COLOR';
export const TOKEN_DATE_TIME = 'TOKEN_DATE_TIME';
export const TOKEN_DATE_TIME_BACKWARDS = 'TOKEN_DATE_TIME_BACKWARDS';
export const TOKEN_NOOP = 'TOKEN_NOOP';
